# Generated by Django 4.2.7 on 2025-08-19 04:30

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='credit_months',
            field=models.JSONField(default=products.models.default_credit_months, verbose_name='Kredit muddatlari'),
        ),
    ]
